# ========================
# DEV ENVIRONMENT
# ========================
FROM node:22-alpine

WORKDIR /app

# Copia package.json para instalar dependências
COPY package*.json ./

RUN npm install

# Copia o restante do código
COPY . .

EXPOSE 3000

# Hot reload no TypeScript
CMD ["npm", "run", "dev"]
